### PR TITLE
Linting & Code Cleanup

### PR DESCRIPTION
**Pull request by nathfreder**
This pull request adds linting, and better maintainability. The _dev-prettier_ script will run a code cleaner to fix all styling issues regarding linting.. I have chose the Google Style Guidelines, but their are others to such as the AirBnB Style Guidelines

### CODE REVIEW

**Comment by nathfreder** [comment]
Requesting review from @drewsucksatlife

**Comment by drewsucksatlife** [comment]
I see no code clean-up, but I will look into these changes.

**Comment by nathfreder** [comment]
The new re-write has (most of)+these changes, although the config is not there.

**Comment by drewsucksatlife** [comment]
I'll add the config to the rewrite, your PR will remain open until these changes are merged.

**Comment by drewsucksatlife** [comment]
@nathfreder The config has been added as of https://github.com/drewsucksatlife/DrooBot/commit/4509bfa0315a543a244bffdf39dc5b2d7e006a9c

**Comment by nathfreder** [comment]
Closing due to conflicts and completion in https://github.com/drewsucksatlife/DrooBot/commit/4509bfa0315a543a244bffdf39dc5b2d7e006a9c.

**Pull request closed without merging**
